import type { ShopItemDef } from './types';

/** Shop catalog — ≥6 categories with prerequisite chains. */
export const SHOP_CATALOG: ShopItemDef[] = [
  {
    id: 'hire_operator',
    category: 'personnel',
    nameKey: 'shop.items.operator.name',
    descriptionKey: 'shop.items.operator.desc',
    price: 180,
    upkeep: 12,
    prerequisites: [],
    roleId: 'operator',
    zoneId: 'machine',
  },
  {
    id: 'hire_assembler',
    category: 'personnel',
    nameKey: 'shop.items.assembler.name',
    descriptionKey: 'shop.items.assembler.desc',
    price: 160,
    upkeep: 11,
    prerequisites: ['hire_operator'],
    roleId: 'assembler',
    zoneId: 'worker',
  },
  {
    id: 'hire_mechanic',
    category: 'personnel',
    nameKey: 'shop.items.mechanic.name',
    descriptionKey: 'shop.items.mechanic.desc',
    price: 220,
    upkeep: 15,
    prerequisites: [],
    roleId: 'mechanic',
    zoneId: 'machine',
  },
  {
    id: 'hire_hopper',
    category: 'personnel',
    nameKey: 'shop.items.hopper.name',
    descriptionKey: 'shop.items.hopper.desc',
    price: 150,
    upkeep: 10,
    prerequisites: [],
    roleId: 'material_handler',
    zoneId: 'hopper',
  },
  {
    id: 'hire_forklift',
    category: 'personnel',
    nameKey: 'shop.items.forklift.name',
    descriptionKey: 'shop.items.forklift.desc',
    price: 200,
    upkeep: 14,
    prerequisites: ['hire_hopper'],
    roleId: 'forklift_driver',
    zoneId: 'hopper',
  },
  {
    id: 'mgr_foreman',
    category: 'managers',
    nameKey: 'shop.items.foreman.name',
    descriptionKey: 'shop.items.foreman.desc',
    price: 350,
    upkeep: 28,
    prerequisites: ['hire_operator'],
    minTutorialStep: 3,
    roleId: 'foreman',
    zoneId: 'machine',
  },
  {
    id: 'mgr_shift_lead',
    category: 'managers',
    nameKey: 'shop.items.shiftLead.name',
    descriptionKey: 'shop.items.shiftLead.desc',
    price: 520,
    upkeep: 40,
    prerequisites: ['mgr_foreman', 'hire_assembler'],
    roleId: 'shift_lead',
    zoneId: 'worker',
  },
  {
    id: 'mat_raw_stock',
    category: 'materials',
    nameKey: 'shop.items.rawStock.name',
    descriptionKey: 'shop.items.rawStock.desc',
    price: 120,
    upkeep: 4,
    prerequisites: [],
    incomeBonus: 0.3,
  },
  {
    id: 'mat_spare_parts',
    category: 'materials',
    nameKey: 'shop.items.spareParts.name',
    descriptionKey: 'shop.items.spareParts.desc',
    price: 150,
    upkeep: 6,
    prerequisites: ['mat_raw_stock'],
    incomeBonus: 0.2,
  },
  {
    id: 'mat_packaging',
    category: 'materials',
    nameKey: 'shop.items.packaging.name',
    descriptionKey: 'shop.items.packaging.desc',
    price: 90,
    upkeep: 3,
    prerequisites: ['mat_raw_stock'],
    incomeBonus: 0.15,
  },
  {
    id: 'struct_assembly_hall',
    category: 'structures',
    nameKey: 'shop.items.assemblyHall.name',
    descriptionKey: 'shop.items.assemblyHall.desc',
    price: 800,
    upkeep: 35,
    prerequisites: ['mgr_foreman', 'mat_raw_stock'],
    capacityBonus: 2,
    incomeBonus: 0.8,
  },
  {
    id: 'struct_raw_warehouse',
    category: 'structures',
    nameKey: 'shop.items.rawWarehouse.name',
    descriptionKey: 'shop.items.rawWarehouse.desc',
    price: 650,
    upkeep: 28,
    prerequisites: ['mat_raw_stock'],
    capacityBonus: 1.5,
    incomeBonus: 0.5,
  },
  {
    id: 'equip_sensor_kit',
    category: 'equipment',
    nameKey: 'shop.items.sensorKit.name',
    descriptionKey: 'shop.items.sensorKit.desc',
    price: 280,
    upkeep: 8,
    prerequisites: ['hire_operator'],
    incomeBonus: 0.25,
  },
  {
    id: 'equip_forklift',
    category: 'equipment',
    nameKey: 'shop.items.forkliftEquip.name',
    descriptionKey: 'shop.items.forkliftEquip.desc',
    price: 420,
    upkeep: 18,
    prerequisites: ['hire_forklift'],
    incomeBonus: 0.35,
  },
  {
    id: 'infra_road_segment',
    category: 'infrastructure',
    nameKey: 'shop.items.roadSegment.name',
    descriptionKey: 'shop.items.roadSegment.desc',
    price: 200,
    upkeep: 5,
    prerequisites: [],
    incomeBonus: 0.2,
  },
  {
    id: 'infra_second_gate',
    category: 'infrastructure',
    nameKey: 'shop.items.secondGate.name',
    descriptionKey: 'shop.items.secondGate.desc',
    price: 380,
    upkeep: 10,
    prerequisites: ['infra_road_segment'],
    incomeBonus: 0.3,
  },
  {
    id: 'upg_standard_work',
    category: 'upgrades',
    nameKey: 'shop.items.standardWork.name',
    descriptionKey: 'shop.items.standardWork.desc',
    price: 300,
    upkeep: 6,
    prerequisites: ['mgr_foreman'],
    incomeBonus: 0.4,
  },
  {
    id: 'upg_visual_mgmt',
    category: 'upgrades',
    nameKey: 'shop.items.visualMgmt.name',
    descriptionKey: 'shop.items.visualMgmt.desc',
    price: 250,
    upkeep: 5,
    prerequisites: ['equip_sensor_kit'],
    incomeBonus: 0.3,
  },
  {
    id: 'upg_cross_train',
    category: 'upgrades',
    nameKey: 'shop.items.crossTrain.name',
    descriptionKey: 'shop.items.crossTrain.desc',
    price: 180,
    upkeep: 4,
    prerequisites: ['hire_assembler'],
    incomeBonus: 0.2,
  },
];

export const SHOP_CATEGORIES: ShopItemDef['category'][] = [
  'personnel',
  'managers',
  'materials',
  'structures',
  'equipment',
  'infrastructure',
  'upgrades',
];

export function catalogById(id: string): ShopItemDef | undefined {
  return SHOP_CATALOG.find((i) => i.id === id);
}

export function catalogByCategory(cat: ShopItemDef['category']): ShopItemDef[] {
  return SHOP_CATALOG.filter((i) => i.category === cat);
}
