import type { ZoneDef } from '@/core/types';

export const ZONE_DEFS: ZoneDef[] = [
  {
    id: 'machine',
    name: 'СТАНОК «АТЛАНТ»',
    gx: 3.0,
    gy: 3.0,
    unlock: 0,
    kind: 'machine',
    gauge: 'T° СТАНКА',
    sensorName: 'ТЕРМОДАТЧИК СТАНКА',
    sensorDesc: 'Перегрев виден за пять секунд до дыма.',
  },
  {
    id: 'hopper',
    name: 'БУНКЕР СЫРЬЯ',
    gx: 8.0,
    gy: 2.5,
    unlock: 15,
    kind: 'hopper',
    gauge: 'СЫРЬЁ',
    sensorName: 'ДАТЧИК УРОВНЯ БУНКЕРА',
    sensorDesc: 'Остаток на виду — линия не встанет «внезапно».',
  },
  {
    id: 'dock',
    name: 'ПОГРУЗОЧНЫЙ ДОК',
    gx: 12.0,
    gy: 8.0,
    unlock: 30,
    kind: 'dock',
    gauge: 'ГРАФИК',
    sensorName: 'GPS-ТЕЛЕМАТИКА РЕЙСОВ',
    sensorDesc: 'График и машины видны — срыв заметен заранее.',
  },
  {
    id: 'press',
    name: 'ПРЕСС «ЦИКЛОП»',
    gx: 3.0,
    gy: 7.5,
    unlock: 50,
    kind: 'press',
    gauge: 'ИЗНОС',
    sensorName: null,
    sensorDesc: null,
  },
  {
    id: 'worker',
    name: 'ПОСТ СБОРКИ',
    gx: 8.0,
    gy: 7.0,
    unlock: 68,
    kind: 'worker',
    gauge: 'СИЛЫ',
    sensorName: null,
    sensorDesc: null,
  },
  {
    id: 'fridge',
    name: 'СКЛАД-ХОЛОД',
    gx: 3.0,
    gy: 12.0,
    unlock: 88,
    kind: 'fridge',
    gauge: 'T° СКЛАДА',
    sensorName: 'ТЕРМОДАТЧИК СКЛАДА',
    sensorDesc: 'Дрейф холода виден сразу — партия не сгниёт молча.',
  },
  {
    id: 'power',
    name: 'ЭНЕРГОЩИТ',
    gx: 8.0,
    gy: 12.0,
    unlock: 105,
    kind: 'power',
    gauge: 'НАГРУЗКА',
    sensorName: 'СЧЁТЧИК ЭНЕРГИИ',
    sensorDesc: 'Пик виден до того, как выбьет автомат.',
  },
];

export const ZONES_ORDERED = [...ZONE_DEFS].sort(
  (a, b) => a.gx + a.gy - (b.gx + b.gy),
);
