import type { ShopContent } from './shopContent';

export const shopEn: ShopContent = {
  openBtn: 'SHOP',
  closeBtn: 'Close',
  title: 'Factory Shop',
  cash: 'Cash',
  upkeep: 'Upkeep / min',
  bonus: 'Bonus income / s',
  efficiency: 'Team efficiency',
  categories: {
    personnel: 'Personnel',
    managers: 'Managers',
    materials: 'Materials',
    structures: 'Structures',
    equipment: 'Equipment',
    infrastructure: 'Infrastructure',
    upgrades: 'Upgrades',
  },
  buyBtn: 'Purchase',
  assignBtn: 'Assign',
  hireTitle: 'Assign employee',
  zoneLabel: 'Work zone',
  brigadeLabel: 'Brigade',
  orgTitle: 'Org chart',
  journalTitle: 'Event journal',
  block: {
    alreadyOwned: 'Already purchased',
    noMoney: 'Not enough cash',
    tutorialLocked: 'Complete tutorial step first',
    needsDefault: 'Requires prior purchase',
  },
  tutorial: [
    '',
    'Reinvest shift earnings — open the shop.',
    'Hire an operator and assign to the machine zone.',
    'More workers without a foreman create task conflicts.',
    'Hire a foreman and assign to a brigade.',
    'Foreman coordinates routine work — hero gets escalations only.',
  ],
  items: {
    operator: { name: 'Machine operator', desc: 'Runs the press line; reduces manual load.' },
    assembler: { name: 'Assembler', desc: 'Builds units at the assembly post.' },
    mechanic: { name: 'Mechanic', desc: 'Handles breakdowns and preventive maintenance.' },
    hopper: {
      name: 'Hopper attendant',
      desc: 'Keeps the raw bunker topped up when the level drops below average.',
    },
    forklift: { name: 'Forklift driver', desc: 'Hauls raw stock to the hopper and pallets on site.' },
    foreman: { name: 'Foreman', desc: 'Coordinates a brigade (span ≤6).' },
    shiftLead: { name: 'Shift lead', desc: 'Balances multiple brigades on one area.' },
    rawStock: { name: 'Raw material stock', desc: 'Stabilizes input flow.' },
    spareParts: { name: 'Spare parts kit', desc: 'Shortens repair downtime.' },
    packaging: { name: 'Packaging supply', desc: 'Enables outbound shipments.' },
    assemblyHall: { name: 'Assembly hall', desc: '+capacity and income; needs foreman.' },
    rawWarehouse: { name: 'Raw warehouse', desc: 'Buffer for incoming materials.' },
    sensorKit: { name: 'Sensor kit', desc: 'Early warning on critical zones.' },
    forkliftEquip: { name: 'Forklift', desc: 'Equipment for internal logistics.' },
    roadSegment: { name: 'Road segment', desc: 'Improves trip time to the dock.' },
    secondGate: { name: 'Second gate', desc: 'Parallel truck access.' },
    standardWork: { name: 'Standard work', desc: 'Raises discipline across brigades.' },
    visualMgmt: { name: 'Visual management', desc: 'Makes losses visible sooner.' },
    crossTrain: { name: 'Cross-training', desc: 'Improves versatility of assemblers.' },
  },
};
